### ISSUE TITLE
SSL Error while using Ruby 2.3.1

### ISSUE THREAD

**Issue by ethagnawl** [wingrunr21/mindbody-api#35]
I'm seeing the following error when making any request to the MindBody API using Ruby 2.3.1:

```
irb(main):028:0> MindBody::Services::ClassService::get_class_schedules
HTTPI::SSLError: SSL_connect returned=1 errno=0 state=unknown state: certificate verify failed
        from /usr/local/bundle/gems/httpi-2.4.2/lib/httpi/adapter/httpclient.rb:28:in `rescue in request'
        from /usr/local/bundle/gems/httpi-2.4.2/lib/httpi/adapter/httpclient.rb:25:in `request'
        from /usr/local/bundle/gems/httpi-2.4.2/lib/httpi.rb:161:in `request'
        from /usr/local/bundle/gems/httpi-2.4.2/lib/httpi.rb:133:in `post'
        from /usr/local/bundle/gems/savon-2.11.1/lib/savon/operation.rb:94:in `block in call_with_logging'
        from /usr/local/bundle/gems/savon-2.11.1/lib/savon/request_logger.rb:12:in `log'
        from /usr/local/bundle/gems/savon-2.11.1/lib/savon/operation.rb:94:in `call_with_logging'
        from /usr/local/bundle/gems/savon-2.11.1/lib/savon/operation.rb:54:in `call'
        from /usr/local/bundle/gems/savon-2.11.1/lib/savon/client.rb:36:in `call'
        from /usr/local/bundle/bundler/gems/mindbody-api-579af18314d2/lib/mindbody-api/client.rb:18:in `call'
        from /usr/local/bundle/bundler/gems/mindbody-api-579af18314d2/lib/mindbody-api/ext/savon_ext.rb:16:in `get_class_schedules'
        from (irb):28
        from /usr/local/bundle/gems/railties-5.0.0/lib/rails/commands/console.rb:65:in `start'
        from /usr/local/bundle/gems/railties-5.0.0/lib/rails/commands/console_helper.rb:9:in `start'
        from /usr/local/bundle/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:78:in `console'
        from /usr/local/bundle/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
        from /usr/local/bundle/gems/railties-5.0.0/lib/rails/commands.rb:18:in `<top (required)>'
        from bin/rails:9:in `require'
        from bin/rails:9:in `<main>'
```

Has anyone else seen this issue? I'd be happy to provide any additional information that might be useful.

**Comment by ethagnawl** [comment]
The problem was on my side. My Docker container was missing libssl-dev.
